SCREEN_HEIGHT = 1200
SCREEN_WIDTH = 1200
NUM_OF_ROWS = 8
NUM_OF_COLS = 8

BACKGROUND_COLOR = (168, 168, 168)
COLORS = {
     'WHITE': (0, 0, 0)
    ,'BLACK': (0, 0, 0)
    ,'GREY' : (128, 128, 128)
    ,'GOLD' : (255, 201, 14)
    }
PAWN_HEIGHT_SCALE = 0.0625
PAWN_WIDTH_SCALE = 0.075
ROOK_HEIGHT_SCALE = 0.08333333
ROOK_WIDTH_SCALE = 0.0916666
KNIGHT_HEIGHT_SCALE = 0.0916666
KNIGHT_WIDTH_SCALE = 0.0916666
BIG_PIECE_HEIGHT_SCALE = 0.1083333
BIG_PIECE_WIDTH_SCALE = 0.1
DOT_SCALE = 0.025
STRIKE_DOT_SCALE = 0.12
CASTLE_DOT_SCALE = 0.05
FONT_SCALE = 0.08

PAWN_IMAGE_SIZE = (SCREEN_HEIGHT * PAWN_HEIGHT_SCALE, SCREEN_WIDTH * PAWN_WIDTH_SCALE)
ROOK_IMAGE_SIZE = (SCREEN_HEIGHT * ROOK_HEIGHT_SCALE, SCREEN_WIDTH * ROOK_WIDTH_SCALE)
KNIGHT_IMAGE_SIZE = (SCREEN_HEIGHT * KNIGHT_HEIGHT_SCALE, SCREEN_WIDTH * KNIGHT_WIDTH_SCALE)
BIG_PIECE_IMAGE_SIZE = (SCREEN_HEIGHT * BIG_PIECE_HEIGHT_SCALE, SCREEN_WIDTH * BIG_PIECE_WIDTH_SCALE)
DOT_IMAGE_SIZE = (SCREEN_HEIGHT * DOT_SCALE, SCREEN_WIDTH * DOT_SCALE)
STRIKED_DOT_IMAGE_SIZE = (SCREEN_HEIGHT * STRIKE_DOT_SCALE, SCREEN_WIDTH * STRIKE_DOT_SCALE)
CASTLE_DOT_IMAGE_SIZE = (SCREEN_HEIGHT * CASTLE_DOT_SCALE, SCREEN_WIDTH * CASTLE_DOT_SCALE)
END_SCREEN_IMAGE_SIZE = ((SCREEN_HEIGHT / 2), (SCREEN_WIDTH / 2))
#SKULL_IMAGE_SIZE = (SCREEN_HEIGHT / NUM_OF_COLS, SCREEN_WIDTH / NUM_OF_ROWS)

''' 
DIT MOET NOG GEFIXT. HARD CODED
!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@!@
'''
END_SCREEN_TEXT_TOP = 200, 50, 400, 50 
END_SCREEN_TEXT_BOTTOM = 200, 650, 400, 50

INPUT_BOX = (SCREEN_WIDTH / 2), (SCREEN_HEIGHT / 2), (SCREEN_HEIGHT * 0,2), (SCREEN_WIDTH * 0,8)
print(INPUT_BOX)